version: "3"
services:
#  db:
#    image: mysql
#    environment:
#      - MYSQL_PASSWORD=secret
#      - MYSQL_ROOT_PASSWORD=root
#    volumes:
#      - ./data/db:/var/lib/mysql
#    ports:
#      - "3306:3306"
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    environment:
#      PMA_ARBITRARY: 1
#      MYSQL_PASSWORD: secret
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#      - "8080:80"
  redis:
    image: redis
    hostname: redis
  bot:
    hostname: bot
    build: .
    ports:
      - "80:80"
    command: sh -c 'NODE_ENV=production DEBUG=bnb:* pm2-runtime start app/server.js'
